-- =========================================================
-- Oracle 11g Schema for AI Cognitive Support System
-- =========================================================

-- 1. USERS
CREATE TABLE USERS (
    USER_ID VARCHAR2(36) PRIMARY KEY,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    ROLE VARCHAR2(20) NOT NULL, -- 'PATIENT' or 'CAREGIVER'
    FULL_NAME VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    FCM_TOKEN VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. PATIENTS
CREATE TABLE PATIENTS (
    PATIENT_ID VARCHAR2(36) PRIMARY KEY,
    AGE NUMBER(3),
    DIAGNOSIS_STAGE VARCHAR2(50),
    CURRENT_DIFFICULTY NUMBER(1) DEFAULT 1, -- 1=Easy, 2=Medium, 3=Hard
    EMERGENCY_CONTACT VARCHAR2(20),
    QR_CODE_TOKEN VARCHAR2(100) UNIQUE,
    CONSTRAINT FK_PATIENT_USER FOREIGN KEY (PATIENT_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 3. CAREGIVERS
CREATE TABLE CAREGIVERS (
    CAREGIVER_ID VARCHAR2(36) PRIMARY KEY,
    RELATION_TYPE VARCHAR2(50),
    CONSTRAINT FK_CAREGIVER_USER FOREIGN KEY (CAREGIVER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. PATIENT_CAREGIVER_MAP
CREATE TABLE PATIENT_CAREGIVER_MAP (
    MAP_ID VARCHAR2(36) PRIMARY KEY,
    PATIENT_ID VARCHAR2(36) NOT NULL,
    CAREGIVER_ID VARCHAR2(36) NOT NULL,
    PAIRED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MAP_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MAP_CAREGIVER FOREIGN KEY (CAREGIVER_ID) REFERENCES CAREGIVERS(CAREGIVER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PATIENT_CAREGIVER UNIQUE (PATIENT_ID, CAREGIVER_ID)
);

-- 5. GAME_SESSIONS
CREATE TABLE GAME_SESSIONS (
    SESSION_ID VARCHAR2(36) PRIMARY KEY,
    PATIENT_ID VARCHAR2(36) NOT NULL,
    GAME_TYPE VARCHAR2(50) DEFAULT 'PATTERN_MEMORY',
    LEVEL_PLAYED NUMBER(1) NOT NULL,
    ACCURACY_RATE NUMBER(5, 4) NOT NULL,
    AVG_REACTION_TIME_MS NUMBER(8, 2) NOT NULL,
    ERROR_COUNT NUMBER(5) NOT NULL,
    COMPLETION_TIME_SEC NUMBER(8, 2) NOT NULL,
    CONSISTENCY_SCORE NUMBER(5, 4) NOT NULL,
    COGNITIVE_STATE VARCHAR2(50) NOT NULL,
    RECOMMENDED_LEVEL NUMBER(1) NOT NULL,
    SESSION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SYNCED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SESSION_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE
);

-- 6. EMERGENCY_ALERTS
CREATE TABLE EMERGENCY_ALERTS (
    ALERT_ID VARCHAR2(36) PRIMARY KEY,
    PATIENT_ID VARCHAR2(36) NOT NULL,
    ALERT_TYPE VARCHAR2(50) NOT NULL,
    MESSAGE VARCHAR2(500) NOT NULL,
    SEVERITY VARCHAR2(20) DEFAULT 'HIGH',
    IS_ACKNOWLEDGED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ALERT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE
);

-- 7. OTP_VERIFICATIONS
CREATE TABLE OTP_VERIFICATIONS (
    EMAIL VARCHAR2(100) PRIMARY KEY,
    OTP_CODE VARCHAR2(6) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
