"""
Train Random Forest ML Model for Dynamic Cognitive Difficulty Adaptation
in Dementia Care. Generates clinical synthetic telemetry, trains RandomForestClassifier,
and exports the ensemble trees directly to pure Dart code for zero-overhead on-device inference.
"""

import os
import sys
import json
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Ensure utf-8 output handling
sys.stdout.reconfigure(encoding='utf-8')

def generate_cognitive_dataset(n_samples=12000, random_seed=42):
    np.random.seed(random_seed)
    
    # Levels: 0=Easy, 1=Medium, 2=Hard
    # Next Target: 0=Easy, 1=Medium, 2=Hard
    
    features = []
    labels = []
    
    for _ in range(n_samples):
        # Current level played
        curr_lvl = np.random.choice([0, 1, 2], p=[0.45, 0.35, 0.20])
        
        # Patient archetype:
        # 0: Struggling/Fatigued, 1: Stable/Adequate, 2: Thriving/High-Recall
        archetype = np.random.choice([0, 1, 2], p=[0.35, 0.40, 0.25])
        
        if archetype == 0:  # Struggling
            accuracy = np.clip(np.random.normal(45, 12), 10, 65)
            mistakes = int(np.clip(np.random.normal(9, 3), 4, 20))
            time_sec = float(np.clip(np.random.normal(85, 25), 35, 180))
            score = float(np.clip(np.random.normal(40, 15), 10, 60))
            
            # Label: Stay or Downgrade to Easy
            target = 0
            
        elif archetype == 1:  # Stable / Moderate
            accuracy = np.clip(np.random.normal(72, 8), 55, 88)
            mistakes = int(np.clip(np.random.normal(3.5, 1.5), 1, 7))
            time_sec = float(np.clip(np.random.normal(45, 12), 20, 80))
            score = float(np.clip(np.random.normal(75, 10), 60, 88))
            
            # Label: If currently easy and doing very well -> Medium. If hard and struggling -> Medium. Else stay or Medium.
            if curr_lvl == 0 and accuracy > 78 and time_sec < 40:
                target = 1
            elif curr_lvl == 2 and (accuracy < 70 or mistakes > 4):
                target = 1
            else:
                target = curr_lvl  # maintain balance
                
        else:  # Thriving / Sharp Recall
            accuracy = np.clip(np.random.normal(92, 5), 82, 100)
            mistakes = int(np.clip(np.random.normal(1.0, 0.8), 0, 3))
            time_sec = float(np.clip(np.random.normal(22, 7), 8, 45))
            score = float(np.clip(np.random.normal(94, 5), 85, 100))
            
            # Label: Upgrade to Hard or Medium
            if curr_lvl == 0:
                target = 1 if time_sec > 25 else 2
            elif curr_lvl == 1:
                target = 2
            else:
                target = 2
        
        # Add 3% random noise/outliers to simulate sensor glitch or erratic tapping
        if np.random.rand() < 0.03:
            target = np.random.choice([0, 1, 2])
            
        features.append([score, time_sec, accuracy, mistakes, curr_lvl])
        labels.append(target)
        
    return np.array(features), np.array(labels)

def export_trees_to_dart(rf_model, feature_names, class_names, output_dart_path):
    """
    Serializes scikit-learn RandomForestClassifier trees into structured Dart code.
    """
    trees_data = []
    
    for tree_idx, estimator in enumerate(rf_model.estimators_):
        tree = estimator.tree_
        
        nodes = []
        for node_id in range(tree.node_count):
            is_leaf = tree.children_left[node_id] == -1 and tree.children_right[node_id] == -1
            if is_leaf:
                # Class distribution counts at leaf
                value_counts = tree.value[node_id][0].tolist()
                predicted_class = int(np.argmax(value_counts))
                nodes.append({
                    "isLeaf": True,
                    "predClass": predicted_class,
                    "weights": [round(float(v), 2) for v in value_counts],
                })
            else:
                nodes.append({
                    "isLeaf": False,
                    "featIdx": int(tree.feature[node_id]),
                    "thresh": round(float(tree.threshold[node_id]), 4),
                    "left": int(tree.children_left[node_id]),
                    "right": int(tree.children_right[node_id]),
                })
        trees_data.append(nodes)
    
    # Generate Dart Source File with escaped raw string for JSON
    json_trees = json.dumps(trees_data)
    
    dart_code = f"""// AUTO-GENERATED BY scripts/train_random_forest.py
// Scikit-Learn RandomForestClassifier with {len(rf_model.estimators_)} Decision Trees.
// Do not edit manually.

import 'dart:convert';

class DecisionNode {{
  final bool isLeaf;
  final int? predClass;
  final List<double>? weights;
  final int? featIdx;
  final double? thresh;
  final int? left;
  final int? right;

  const DecisionNode({{
    required this.isLeaf,
    this.predClass,
    this.weights,
    this.featIdx,
    this.thresh,
    this.left,
    this.right,
  }});

  factory DecisionNode.fromMap(Map<String, dynamic> map) {{
    return DecisionNode(
      isLeaf: map['isLeaf'] as bool,
      predClass: map['predClass'] as int?,
      weights: (map['weights'] as List<dynamic>?)
          ?.map((e) => (e as num).toDouble())
          .toList(),
      featIdx: map['featIdx'] as int?,
      thresh: (map['thresh'] as num?)?.toDouble(),
      left: map['left'] as int?,
      right: map['right'] as int?,
    );
  }}
}}

class RandomForestModelData {{
  static const int numTrees = {len(rf_model.estimators_)};
  static const List<String> featureNames = {feature_names};
  static const List<String> classNames = {class_names};

  static final List<List<DecisionNode>> trees = _loadTrees();

  static List<List<DecisionNode>> _loadTrees() {{
    const String rawJson = r'''{json_trees}''';
    final List<dynamic> parsed = jsonDecode(rawJson);
    return parsed.map((treeList) {{
      return (treeList as List<dynamic>)
          .map((n) => DecisionNode.fromMap(n as Map<String, dynamic>))
          .toList();
    }}).toList();
  }}
}}
"""
    os.makedirs(os.path.dirname(output_dart_path), exist_ok=True)
    with open(output_dart_path, 'w', encoding='utf-8') as f:
        f.write(dart_code)
    print(f"[SUCCESS] Exported Random Forest model to Dart: {output_dart_path}")

def main():
    print("[INFO] Generating clinical dementia gameplay telemetry dataset...")
    X, y = generate_cognitive_dataset(n_samples=12000)
    
    feature_names = ["score", "time_sec", "accuracy", "mistakes", "current_level"]
    class_names = ["EASY", "MEDIUM", "HARD"]
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )
    
    print(f"[INFO] Training set: {X_train.shape[0]} samples, Test set: {X_test.shape[0]} samples")
    print("[INFO] Training RandomForestClassifier (n_estimators=50, max_depth=6)...")
    
    rf = RandomForestClassifier(
        n_estimators=50,
        max_depth=6,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(X_train, y_train)
    
    y_pred = rf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"[EVAL] Test Accuracy: {accuracy * 100:.2f}%")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))
    
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    
    print("\nFeature Importances:")
    for name, imp in zip(feature_names, rf.feature_importances_):
        print(f"  - {name:15s}: {imp * 100:.2f}%")
        
    output_dart_path = os.path.join(
        "D:\\ElderlyCareProject", "flutter_app", "lib", "services", "ml_difficulty_trees.dart"
    )
    export_trees_to_dart(rf, feature_names, class_names, output_dart_path)
    
if __name__ == "__main__":
    main()
